# Use the official Locust image as the base
FROM locustio/locust

# Set the working directory in the container
WORKDIR /app

# Copy the local locustfile.py to the container
COPY locustfile.py .

# Set the default command for the container
CMD ["--worker", "-f", "locustfile.py", "--master-host", "locust-master"]
