version: "3.9"
services:
  backend0:
    build:
      context: backend
    environment:
      - PORT=9000
    expose:
      - 9000
    networks:
      - net-backend
  backend1:
    build:
      context: backend
    environment:
      - PORT=9001
    expose:
      - 9001
    networks:
      - net-backend
  backend2:
    build:
      context: backend
    environment:
      - PORT=9002
    expose:
      - 9002
    networks:
      - net-backend
  backend3:
    build:
      context: backend
    environment:
      - PORT=9003
    expose:
      - 9003
    networks:
      - net-backend
  backend4:
    build:
      context: backend
    environment:
      - PORT=9004
    expose:
      - 9004
    networks:
      - net-backend
  backend5:
    build:
      context: backend
    environment:
      - PORT=9005
    expose:
      - 9005
    networks:
      - net-backend
  backend6:
    build:
      context: backend
    environment:
      - PORT=9006
    expose:
      - 9006
    networks:
      - net-backend
  backend7:
    build:
      context: backend
    environment:
      - PORT=9007
    expose:
      - 9007
    networks:
      - net-backend
  
  frontend:
    build:
      context: frontend
    expose:
      - 8080
    networks:
      - net-frontend
      - net-backend
    depends_on:
      - backend0
      - backend1
      - backend2
      - backend3
      - backend4
      - backend5
      - backend6
      - backend7

  proxy:
    image: nginx:1.23.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    networks:
      - net-frontend
    depends_on:
      - frontend

networks:
  net-frontend:
    driver: bridge
  net-backend:
    driver: bridge
