version: "3.9"
services:
  backend:
    build:
      context: backend
    environment:
      - PORT=9000
    expose:
      - 9000
  frontend:
    build:
      context: frontend
    expose:
      - 8080
    depends_on:
      - backend
  locust:
    build:
      context: locust
    expose:
      - 5557
      - 5558
    ports:
      - "8089:8089"
    depends_on:
      - frontend
  proxy:
    image: nginx:1.23.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    depends_on:
      - frontend

