version: "3.9"
services:
  backend:
    build:
      context: backend
    environment:
      - PORT=9000
    expose:
      - 9000
    networks:
      - storage
  frontend:
    build:
      context: frontend
    expose:
      - 8080
    networks:
      - storage
    depends_on:
      - backend
  locust-master:
    build:
      context: locust
      dockerfile: Dockerfile.master
    expose:
      - 5557
      - 5558
    ports:
      - "8089:8089"
    networks:
      - storage
    depends_on:
      - frontend
  locust-worker:
    build:
      context: locust
      dockerfile: Dockerfile.worker
    networks:
      - storage
    depends_on:
      - locust-master
  proxy:
    image: nginx:1.23.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    networks:
      - storage
    depends_on:
      - frontend

networks:
  storage:
    driver: bridge
