version: "3.9"
services:
  backend0:
    build:
      context: backend
    expose:
      - 9000
    networks:
      - net-backend
  backend1:
    build:
      context: backend
    expose:
      - 9000
    networks:
      - net-backend
  backend2:
    build:
      context: backend
    expose:
      - 9000
    networks:
      - net-backend
  backend3:
    build:
      context: backend
    expose:
      - 9000
    networks:
      - net-backend
  backend4:
    build:
      context: backend
    expose:
      - 9000
    networks:
      - net-backend
  backend5:
    build:
      context: backend
    expose:
      - 9000
    networks:
      - net-backend
  backend6:
    build:
      context: backend
    expose:
      - 9000
    networks:
      - net-backend
  backend7:
    build:
      context: backend
    expose:
      - 9000
    networks:
      - net-backend
  #backend8:
  #  build:
  #    context: backend
  #  expose:
  #    - 9000
  #  networks:
  #    - net-backend
  #backend9:
  #  build:
  #    context: backend
  #  expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend10:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend11:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend12:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend13:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend14:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend15:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend16:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend17:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend18:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend
  #ackend19:
  # build:
  #   context: backend
  # expose:
  #   - 9000
  # networks:
  #   - net-backend

  frontend:
    build:
      context: frontend
    expose:
      - 8080
    networks:
      - net-frontend
      - net-backend
    depends_on:
      - backend0
      - backend1
      - backend2
      - backend3
      - backend4
      - backend5
      - backend6
      - backend7
      #- backend8
      #- backend9
      #- backend10
      #- backend11
      #- backend12
      #- backend13
      #- backend14
      #- backend15
      #- backend16
      #- backend17
      #- backend18
      #- backend19

  proxy:
    image: nginx:1.23.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    networks:
      - net-frontend
    depends_on:
      - frontend

networks:
  net-frontend:
    driver: bridge
  net-backend:
    driver: bridge
